class_name Events

const TIME_CONTROL_PLAY_PRESSED = "TIME_CONTROL_PLAY_PRESSED"
const TIME_CONTROL_PAUSE_PRESSED = "TIME_CONTROL_PAUSE_PRESSED"
const TIME_CONTROL_SLOWER_PRESSED = "TIME_CONTROL_SLOWER_PRESSED"
const TIME_CONTROL_FASTER_PRESSED = "TIME_CONTROL_FASTER_PRESSED"

const BODY_HOVERED = "BODY_HOVERED"
const BODY_SELECTED = "BODY_SELECTED"

const CAMERA_ALTITUDE_CHANGED = "CAMERA_ALTITUDE_CHANGED"
